import { pathToFileURL } from 'node:url';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const base = process.env.THERMALSCOPE_URL || 'http://localhost:8088';
const output = resolve(process.env.THERMALSCOPE_SCREENSHOTS || './tools/screenshots');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
let checks = 0;
function check(value, message) { if (!value) throw new Error(message); checks++; }
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
  await page.goto(base); await page.waitForFunction(() => document.getElementById('cpuTemp').textContent !== '—');
  check(await page.locator('#connection').innerText() === 'Live · 1 sec', 'Live connection missing.');
  check(await page.locator('#gpuTemp').innerText() !== '—', 'GPU reading missing.');
  check(await page.locator('#cpuFan').innerText() !== '—', 'CPU fan reading missing.');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Desktop layout overflows.');
  await page.screenshot({ path: resolve(output, 'desktop.png'), fullPage: true });
  await page.getByRole('button', { name: 'Sensor setup', exact: true }).click();
  await page.waitForSelector('#mapping-fields select');
  check(await page.locator('#sensor-table').innerText().then(t => t.includes('CPU Fan')), 'Motherboard fan not shown.');
  check(await page.locator('select[data-key="cpuFan"]').locator('option').first().innerText().then(t => t.includes('CPU Fan')), 'Automatic fan mapping not reflected in setup.');
  await page.getByRole('button', { name: 'Live dashboard', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Phone layout overflows.');
  await page.screenshot({ path: resolve(output, 'iphone.png'), fullPage: true });
  await page.locator('#focus').click();
  check(await page.locator('body').evaluate(el => el.classList.contains('focus')), 'Focus mode failed.');
  check(await page.locator('nav').isHidden(), 'Focus navigation should be hidden.');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Phone focus layout overflows.');
  await page.screenshot({ path: resolve(output, 'iphone-focus.png'), fullPage: true });
  await page.setViewportSize({ width: 844, height: 390 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Landscape layout overflows.');
  await page.screenshot({ path: resolve(output, 'iphone-landscape.png'), fullPage: true });
  await page.locator('#focus').click();
  // Simulate network loss without stopping the collector or writing real sessions.
  await page.route('**/api/live', route => route.abort());
  await page.waitForFunction(() => document.getElementById('connection').textContent.includes('Reconnecting'));
  check(await page.locator('#cpuTemp').innerText() === '—', 'Stale reading should not look live.');
  check(await page.locator('#start').isDisabled(), 'Recording start must be disabled while disconnected.');
  await page.unroute('**/api/live');
  await page.waitForFunction(() => document.getElementById('connection').textContent.includes('Live'));
  check(await page.locator('#cpuTemp').innerText() !== '—', 'Connection recovery failed.');
  // Exercise comparison rendering with explicitly simulated fixtures, without changing the real database.
  const frames = await page.request.get(base + '/api/history').then(r => r.json());
  const firstTime = frames[0]?.time || new Date().toISOString();
  const fixture = (id, cooler, delta) => {
    const modified = frames.map(f => ({ ...f, metrics: { ...f.metrics, cpuTemp: f.metrics.cpuTemp == null ? null : f.metrics.cpuTemp + delta } }));
    const session = { id, name: 'UI TEST · ' + cooler, cooler, game: 'Simulated comparison', notes: '', started: firstTime, ended: modified.at(-1)?.time, ambient: 24, minutes: 60, status: 'completed', samples: modified.length };
    const summary = Object.fromEntries(['cpuTemp', 'gpuTemp', 'gpuHotspot', 'cpuFan', 'gpuFan', 'pumpFan', 'systemFans', 'cpuPower', 'gpuPower', 'cpuLoad', 'gpuLoad', 'ramUsed', 'fps', 'frameTime'].map(key => {
      const values = modified.map(f => f.metrics[key]).filter(v => v != null), average = values.length ? values.reduce((a, b) => a + b, 0) / values.length : null;
      return [key, { count: values.length, average, peak: values.length ? Math.max(...values) : null, final15Average: average }];
    }));
    return { session, frames: modified, summary };
  };
  const fixtures = Object.fromEntries(Array.from({ length: 10 }, (_, i) => {
    const id = String.fromCharCode(97 + i); return [id, fixture(id, `Custom setup ${i + 1}`, -i)];
  }));
  fixtures.c.session.name = '<script>Not executable</script> · custom run';
  fixtures.c.session.cooler = '';
  fixtures.c.summary.cpuTemp = { count: 0, average: null, peak: null, final15Average: null };
  fixtures.c.frames = fixtures.c.frames.map(f => ({ ...f, metrics: { ...f.metrics, cpuTemp: null } }));
  await page.route('**/api/sessions*', async route => {
    const url = new URL(route.request().url());
    await route.fulfill({ json: url.pathname === '/api/sessions' ? Object.values(fixtures).map(f => f.session) : fixtures[url.pathname.split('/').at(-1)] });
  });
  await page.route('**/api/sessions/*', async route => { await route.fulfill({ json: fixtures[new URL(route.request().url()).pathname.split('/').at(-1)] }); });
  await page.getByRole('button', { name: 'Sessions', exact: true }).click();
  await page.waitForSelector('.session-row:nth-child(10)');
  check(await page.locator('#compare-chart').isHidden(), 'Comparison must have its own view.');
  await page.getByRole('button', { name: 'Compare', exact: true }).click();
  await page.waitForSelector('#compare-session-list input[value="a"]');
  for (const id of ['a', 'b', 'c']) await page.locator(`#compare-session-list input[value="${id}"]`).check();
  await page.waitForSelector('.stat-box:nth-child(3)');
  check(await page.locator('.stat-box').count() === 3, 'Multi-session summaries missing.');
  check(await page.locator('#comparison-info').innerText().then(t => t.includes(fixtures.c.session.name)), 'Custom names should render as text.');
  check(await page.locator('.stat-box').nth(2).innerText().then(t => t.includes('— °C')), 'Missing values should not display as zero.');
  await page.locator('#compare-search').fill('Custom setup 10');
  check(await page.locator('#compare-session-list input').count() === 1, 'Session search failed.');
  check(await page.locator('#compare-selected-count').innerText() === '3 selected', 'Search must preserve selection.');
  await page.locator('#compare-search').fill('');
  for (const id of ['d', 'e', 'f', 'g', 'h', 'i', 'j']) await page.locator(`#compare-session-list input[value="${id}"]`).check();
  await page.waitForSelector('.stat-box:nth-child(10)');
  check(await page.locator('.stat-box').count() === 10, 'Comparison should support more than two or eight sessions.');
  check(await page.locator('#compare-metric option').count() === 14, 'All dashboard metrics should be available.');
  await page.locator('#compare-metric').selectOption('gpuPower');
  check(await page.locator('.stat-box').first().innerText().then(t => t.includes(' W')), 'Metric changes should update summary units.');
  await page.locator('#compare-metric').selectOption('fps');
  check(await page.locator('.stat-box').first().innerText().then(t => t.includes(' FPS')), 'Unavailable performance metrics should still render safely.');
  await page.locator('#compare-metric').selectOption('cpuTemp');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Comparison layout overflows.');
  await page.screenshot({ path: resolve(output, 'comparison-landscape.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Phone comparison layout overflows.');
  await page.screenshot({ path: resolve(output, 'comparison-phone.png'), fullPage: true });
  await page.getByRole('button', { name: 'Sessions', exact: true }).click();
  await page.getByRole('button', { name: 'Compare', exact: true }).click();
  await page.waitForSelector('.stat-box:nth-child(10)');
  check(await page.locator('#compare-selected-count').innerText() === '10 selected', 'View changes should preserve selection.');
  await page.locator('#clear-comparison').click();
  check(await page.locator('.stat-box').count() === 0, 'Clear selection failed.');
  await page.getByRole('button', { name: 'Live dashboard', exact: true }).click();
  check(await page.locator('#cooler').evaluate(el => el.tagName === 'INPUT'), 'Cooler must be free text.');
  await page.locator('#session-name').fill('My custom benchmark / quiet fan curve');
  await page.locator('#cooler').fill('A cooler not in any preset');
  await page.locator('#duration').fill('47');
  let submitted;
  await page.route('**/api/sessions/start', async route => {
    submitted = route.request().postDataJSON();
    await route.fulfill({ json: { ...fixtures.a.session, ...submitted, started: new Date().toISOString(), status: 'recording' } });
  });
  await page.locator('#start').click();
  await page.waitForFunction(() => document.getElementById('stop').hidden === false);
  check(submitted?.name === 'My custom benchmark / quiet fan curve' && submitted.cooler === 'A cooler not in any preset' && submitted.minutes === 47, 'Custom session fields not submitted.');
  check(await page.locator('#record-label').innerText().then(t => t.includes(submitted.name)), 'Recording should be identified by its session name.');
  check(errors.length === 0, 'Browser errors: ' + errors.join('; '));
  console.log(`Browser checks passed: ${checks}. Screenshots: ${output}`);
} finally { await browser.close(); }
